package com.lanou.entity;

import java.math.BigDecimal;

public class Exportproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String exportProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String exportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String packingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.BOX_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short boxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal grossWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal netWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal sizeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal sizeWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal sizeHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.EX_PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal exPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.TAX
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_PRODUCT_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @return the value of EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getExportProductId() {
        return exportProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @param exportProductId the value for EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExportProductId(String exportProductId) {
        this.exportProductId = exportProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @return the value of EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getExportId() {
        return exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @param exportId the value for EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExportId(String exportId) {
        this.exportId = exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @return the value of EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @param factoryId the value for EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @return the value of EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @param factoryName the value for EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @return the value of EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @param productNo the value for EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @return the value of EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @param packingUnit the value for EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.CNUMBER
     *
     * @return the value of EXPORT_PRODUCT_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.CNUMBER
     *
     * @param cnumber the value for EXPORT_PRODUCT_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCnumber(Short cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.BOX_NUM
     *
     * @return the value of EXPORT_PRODUCT_C.BOX_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getBoxNum() {
        return boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.BOX_NUM
     *
     * @param boxNum the value for EXPORT_PRODUCT_C.BOX_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setBoxNum(Short boxNum) {
        this.boxNum = boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @return the value of EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getGrossWeight() {
        return grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @param grossWeight the value for EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setGrossWeight(BigDecimal grossWeight) {
        this.grossWeight = grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @return the value of EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getNetWeight() {
        return netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @param netWeight the value for EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setNetWeight(BigDecimal netWeight) {
        this.netWeight = netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @return the value of EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getSizeLength() {
        return sizeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @param sizeLength the value for EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setSizeLength(BigDecimal sizeLength) {
        this.sizeLength = sizeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @return the value of EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getSizeWidth() {
        return sizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @param sizeWidth the value for EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setSizeWidth(BigDecimal sizeWidth) {
        this.sizeWidth = sizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @return the value of EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getSizeHeight() {
        return sizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @param sizeHeight the value for EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setSizeHeight(BigDecimal sizeHeight) {
        this.sizeHeight = sizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.EX_PRICE
     *
     * @return the value of EXPORT_PRODUCT_C.EX_PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getExPrice() {
        return exPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.EX_PRICE
     *
     * @param exPrice the value for EXPORT_PRODUCT_C.EX_PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExPrice(BigDecimal exPrice) {
        this.exPrice = exPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.PRICE
     *
     * @return the value of EXPORT_PRODUCT_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.PRICE
     *
     * @param price the value for EXPORT_PRODUCT_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.TAX
     *
     * @return the value of EXPORT_PRODUCT_C.TAX
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.TAX
     *
     * @param tax the value for EXPORT_PRODUCT_C.TAX
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.ORDER_NO
     *
     * @return the value of EXPORT_PRODUCT_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.ORDER_NO
     *
     * @param orderNo the value for EXPORT_PRODUCT_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }
}