package com.lanou.mapper;

import java.util.List;

import com.lanou.entity.Extcproduct;

public interface ExtcproductMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int deleteByPrimaryKey(String extCproductId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insert(Extcproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insertSelective(Extcproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKey(Extcproduct record);

	Extcproduct selectExtCproductByFactoryId(String id);

	/**
	 * 根据合同id删除附件表
	 * 
	 * @param cProductId
	 * @return
	 */
	int deleteExtCproductBycProductId(String cProductId);

	/**
	 * 查询附件集合
	 * 
	 * @return
	 */
	List<Extcproduct> selectAll(String id);

	/**
	 * 动态修改
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKeySelective(Extcproduct record);

	/**
	 * 根据id查找附件
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	Extcproduct selectByPrimaryKey(String extCproductId);
	/**
	 * 级联删除附件
	 * @param contractProductId
	 * @return
	 */
	int deleteByContractProductId(String contractProductId);
	/**
	 * 根据合同货物id查询附件集合
	 * 
	 * @param contractProductId
	 * @return
	 */
	List<Extcproduct> selectByContractProductId(String contractProductId);
	
}