package com.lanou.mapper;

import com.lanou.entity.Finance;

public interface FinanceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table FINANCE_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insert(Finance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table FINANCE_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKey(Finance record);

	/////////////////////////////////////////////////////////////////////////////////////

	/**
	 * 删除
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int deleteByPrimaryKey(String financeId);

	/**
	 * 根据id查询
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	Finance selectByPrimaryKey(String financeId);

	/**
	 * 增加
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insertSelective(Finance record);

	/**
	 * 修改
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKeySelective(Finance record);

}