package com.lanou.entity;

import java.util.Date;

public class Factory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FULL_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CONTACTS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.PHONE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.MOBILE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FAX
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CNOTE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String cnote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.INSPECTOR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String inspector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FACTORY_ID
     *
     * @return the value of FACTORY_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FACTORY_ID
     *
     * @param factoryId the value for FACTORY_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FULL_NAME
     *
     * @return the value of FACTORY_C.FULL_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FULL_NAME
     *
     * @param fullName the value for FACTORY_C.FULL_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FACTORY_NAME
     *
     * @return the value of FACTORY_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FACTORY_NAME
     *
     * @param factoryName the value for FACTORY_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CONTACTS
     *
     * @return the value of FACTORY_C.CONTACTS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CONTACTS
     *
     * @param contacts the value for FACTORY_C.CONTACTS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.PHONE
     *
     * @return the value of FACTORY_C.PHONE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.PHONE
     *
     * @param phone the value for FACTORY_C.PHONE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.MOBILE
     *
     * @return the value of FACTORY_C.MOBILE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.MOBILE
     *
     * @param mobile the value for FACTORY_C.MOBILE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FAX
     *
     * @return the value of FACTORY_C.FAX
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FAX
     *
     * @param fax the value for FACTORY_C.FAX
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CNOTE
     *
     * @return the value of FACTORY_C.CNOTE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCnote() {
        return cnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CNOTE
     *
     * @param cnote the value for FACTORY_C.CNOTE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCnote(String cnote) {
        this.cnote = cnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.INSPECTOR
     *
     * @return the value of FACTORY_C.INSPECTOR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getInspector() {
        return inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.INSPECTOR
     *
     * @param inspector the value for FACTORY_C.INSPECTOR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInspector(String inspector) {
        this.inspector = inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.ORDER_NO
     *
     * @return the value of FACTORY_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.ORDER_NO
     *
     * @param orderNo the value for FACTORY_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.STATE
     *
     * @return the value of FACTORY_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.STATE
     *
     * @param state the value for FACTORY_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CREATE_BY
     *
     * @return the value of FACTORY_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CREATE_BY
     *
     * @param createBy the value for FACTORY_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CREATE_DEPT
     *
     * @return the value of FACTORY_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CREATE_DEPT
     *
     * @param createDept the value for FACTORY_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CREATE_TIME
     *
     * @return the value of FACTORY_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CREATE_TIME
     *
     * @param createTime the value for FACTORY_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}