package com.lanou.entity;

import java.util.Date;

public class Finance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCE_C.FINANCE_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String financeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCE_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date inputDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCE_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String inputBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.FINANCE_ID
     *
     * @return the value of FINANCE_C.FINANCE_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.FINANCE_ID
     *
     * @param financeId the value for FINANCE_C.FINANCE_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFinanceId(String financeId) {
        this.financeId = financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.INPUT_DATE
     *
     * @return the value of FINANCE_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.INPUT_DATE
     *
     * @param inputDate the value for FINANCE_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.INPUT_BY
     *
     * @return the value of FINANCE_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getInputBy() {
        return inputBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.INPUT_BY
     *
     * @param inputBy the value for FINANCE_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInputBy(String inputBy) {
        this.inputBy = inputBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.STATE
     *
     * @return the value of FINANCE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.STATE
     *
     * @param state the value for FINANCE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.CREATE_BY
     *
     * @return the value of FINANCE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.CREATE_BY
     *
     * @param createBy the value for FINANCE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.CREATE_DEPT
     *
     * @return the value of FINANCE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.CREATE_DEPT
     *
     * @param createDept the value for FINANCE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.CREATE_TIME
     *
     * @return the value of FINANCE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.CREATE_TIME
     *
     * @param createTime the value for FINANCE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}