package com.lanou.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Authuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.AUTH_USER_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String authUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.USERNAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.PASSWORD
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.SALARY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.BIRTHDAY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.GENDER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.STATION
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.TELEPHONE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.DEGREE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.MANAGER_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.AUTH_USER_ID
     *
     * @return the value of AUTH_USER_P.AUTH_USER_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getAuthUserId() {
        return authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.AUTH_USER_ID
     *
     * @param authUserId the value for AUTH_USER_P.AUTH_USER_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setAuthUserId(String authUserId) {
        this.authUserId = authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.USERNAME
     *
     * @return the value of AUTH_USER_P.USERNAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.USERNAME
     *
     * @param username the value for AUTH_USER_P.USERNAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.PASSWORD
     *
     * @return the value of AUTH_USER_P.PASSWORD
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.PASSWORD
     *
     * @param password the value for AUTH_USER_P.PASSWORD
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.SALARY
     *
     * @return the value of AUTH_USER_P.SALARY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.SALARY
     *
     * @param salary the value for AUTH_USER_P.SALARY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.BIRTHDAY
     *
     * @return the value of AUTH_USER_P.BIRTHDAY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.BIRTHDAY
     *
     * @param birthday the value for AUTH_USER_P.BIRTHDAY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.GENDER
     *
     * @return the value of AUTH_USER_P.GENDER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.GENDER
     *
     * @param gender the value for AUTH_USER_P.GENDER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.STATION
     *
     * @return the value of AUTH_USER_P.STATION
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.STATION
     *
     * @param station the value for AUTH_USER_P.STATION
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setStation(String station) {
        this.station = station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.TELEPHONE
     *
     * @return the value of AUTH_USER_P.TELEPHONE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.TELEPHONE
     *
     * @param telephone the value for AUTH_USER_P.TELEPHONE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.REMARK
     *
     * @return the value of AUTH_USER_P.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.REMARK
     *
     * @param remark the value for AUTH_USER_P.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.DEGREE
     *
     * @return the value of AUTH_USER_P.DEGREE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.DEGREE
     *
     * @param degree the value for AUTH_USER_P.DEGREE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.MANAGER_ID
     *
     * @return the value of AUTH_USER_P.MANAGER_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.MANAGER_ID
     *
     * @param managerId the value for AUTH_USER_P.MANAGER_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.CREATE_BY
     *
     * @return the value of AUTH_USER_P.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.CREATE_BY
     *
     * @param createBy the value for AUTH_USER_P.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.CREATE_DEPT
     *
     * @return the value of AUTH_USER_P.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.CREATE_DEPT
     *
     * @param createDept the value for AUTH_USER_P.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.CREATE_TIME
     *
     * @return the value of AUTH_USER_P.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.CREATE_TIME
     *
     * @param createTime the value for AUTH_USER_P.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}