package com.lanou.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Contracthis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.OFFEROR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String offeror;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CONTRACT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String contractNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.SIGNING_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date signingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String inputBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CHECK_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String checkBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.INSPECTOR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String inspector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.TOTAL_AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.IMPORT_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short importNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CREQUEST
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String crequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CUSTOM_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String customName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.DELIVERY_PERIOD
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date deliveryPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.SHIP_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date shipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.TRADE_TERMS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String tradeTerms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.PRINT_STYLE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String printStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.OLD_STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short oldState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.OUT_STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short outState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_HIS_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date createTime;
    
    /**
     * 货物数
     */
    private Short cnumber;
    /**
     * 附件数
     */
    private Short extnum;
    

    public Short getCnumber() {
		return cnumber;
	}

	public void setCnumber(Short cnumber) {
		this.cnumber = cnumber;
	}

	public Short getExtnum() {
		return extnum;
	}

	public void setExtnum(Short extnum) {
		this.extnum = extnum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CONTRACT_ID
     *
     * @return the value of CONTRACT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CONTRACT_ID
     *
     * @param contractId the value for CONTRACT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.OFFEROR
     *
     * @return the value of CONTRACT_HIS_C.OFFEROR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getOfferor() {
        return offeror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.OFFEROR
     *
     * @param offeror the value for CONTRACT_HIS_C.OFFEROR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOfferor(String offeror) {
        this.offeror = offeror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CONTRACT_NO
     *
     * @return the value of CONTRACT_HIS_C.CONTRACT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CONTRACT_NO
     *
     * @param contractNo the value for CONTRACT_HIS_C.CONTRACT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.SIGNING_DATE
     *
     * @return the value of CONTRACT_HIS_C.SIGNING_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getSigningDate() {
        return signingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.SIGNING_DATE
     *
     * @param signingDate the value for CONTRACT_HIS_C.SIGNING_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setSigningDate(Date signingDate) {
        this.signingDate = signingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.INPUT_BY
     *
     * @return the value of CONTRACT_HIS_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getInputBy() {
        return inputBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.INPUT_BY
     *
     * @param inputBy the value for CONTRACT_HIS_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInputBy(String inputBy) {
        this.inputBy = inputBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CHECK_BY
     *
     * @return the value of CONTRACT_HIS_C.CHECK_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCheckBy() {
        return checkBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CHECK_BY
     *
     * @param checkBy the value for CONTRACT_HIS_C.CHECK_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCheckBy(String checkBy) {
        this.checkBy = checkBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.INSPECTOR
     *
     * @return the value of CONTRACT_HIS_C.INSPECTOR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getInspector() {
        return inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.INSPECTOR
     *
     * @param inspector the value for CONTRACT_HIS_C.INSPECTOR
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInspector(String inspector) {
        this.inspector = inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.TOTAL_AMOUNT
     *
     * @return the value of CONTRACT_HIS_C.TOTAL_AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.TOTAL_AMOUNT
     *
     * @param totalAmount the value for CONTRACT_HIS_C.TOTAL_AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.IMPORT_NUM
     *
     * @return the value of CONTRACT_HIS_C.IMPORT_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getImportNum() {
        return importNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.IMPORT_NUM
     *
     * @param importNum the value for CONTRACT_HIS_C.IMPORT_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setImportNum(Short importNum) {
        this.importNum = importNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CREQUEST
     *
     * @return the value of CONTRACT_HIS_C.CREQUEST
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCrequest() {
        return crequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CREQUEST
     *
     * @param crequest the value for CONTRACT_HIS_C.CREQUEST
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCrequest(String crequest) {
        this.crequest = crequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CUSTOM_NAME
     *
     * @return the value of CONTRACT_HIS_C.CUSTOM_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CUSTOM_NAME
     *
     * @param customName the value for CONTRACT_HIS_C.CUSTOM_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCustomName(String customName) {
        this.customName = customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.DELIVERY_PERIOD
     *
     * @return the value of CONTRACT_HIS_C.DELIVERY_PERIOD
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getDeliveryPeriod() {
        return deliveryPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.DELIVERY_PERIOD
     *
     * @param deliveryPeriod the value for CONTRACT_HIS_C.DELIVERY_PERIOD
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setDeliveryPeriod(Date deliveryPeriod) {
        this.deliveryPeriod = deliveryPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.SHIP_TIME
     *
     * @return the value of CONTRACT_HIS_C.SHIP_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.SHIP_TIME
     *
     * @param shipTime the value for CONTRACT_HIS_C.SHIP_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setShipTime(Date shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.TRADE_TERMS
     *
     * @return the value of CONTRACT_HIS_C.TRADE_TERMS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getTradeTerms() {
        return tradeTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.TRADE_TERMS
     *
     * @param tradeTerms the value for CONTRACT_HIS_C.TRADE_TERMS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setTradeTerms(String tradeTerms) {
        this.tradeTerms = tradeTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.REMARK
     *
     * @return the value of CONTRACT_HIS_C.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.REMARK
     *
     * @param remark the value for CONTRACT_HIS_C.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.PRINT_STYLE
     *
     * @return the value of CONTRACT_HIS_C.PRINT_STYLE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPrintStyle() {
        return printStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.PRINT_STYLE
     *
     * @param printStyle the value for CONTRACT_HIS_C.PRINT_STYLE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPrintStyle(String printStyle) {
        this.printStyle = printStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.OLD_STATE
     *
     * @return the value of CONTRACT_HIS_C.OLD_STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getOldState() {
        return oldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.OLD_STATE
     *
     * @param oldState the value for CONTRACT_HIS_C.OLD_STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOldState(Short oldState) {
        this.oldState = oldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.STATE
     *
     * @return the value of CONTRACT_HIS_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.STATE
     *
     * @param state the value for CONTRACT_HIS_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.OUT_STATE
     *
     * @return the value of CONTRACT_HIS_C.OUT_STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getOutState() {
        return outState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.OUT_STATE
     *
     * @param outState the value for CONTRACT_HIS_C.OUT_STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOutState(Short outState) {
        this.outState = outState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CREATE_BY
     *
     * @return the value of CONTRACT_HIS_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CREATE_BY
     *
     * @param createBy the value for CONTRACT_HIS_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CREATE_DEPT
     *
     * @return the value of CONTRACT_HIS_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CREATE_DEPT
     *
     * @param createDept the value for CONTRACT_HIS_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_HIS_C.CREATE_TIME
     *
     * @return the value of CONTRACT_HIS_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_HIS_C.CREATE_TIME
     *
     * @param createTime the value for CONTRACT_HIS_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}