package com.lanou.entity;

import java.math.BigDecimal;

public class Extcproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.EXT_CPRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String extCproductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String contractProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.CTYPE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short ctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String packingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_CPRODUCT_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.EXT_CPRODUCT_ID
     *
     * @return the value of EXT_CPRODUCT_C.EXT_CPRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getExtCproductId() {
        return extCproductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.EXT_CPRODUCT_ID
     *
     * @param extCproductId the value for EXT_CPRODUCT_C.EXT_CPRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExtCproductId(String extCproductId) {
        this.extCproductId = extCproductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @return the value of EXT_CPRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getContractProductId() {
        return contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @param contractProductId the value for EXT_CPRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setContractProductId(String contractProductId) {
        this.contractProductId = contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.FACTORY_ID
     *
     * @return the value of EXT_CPRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.FACTORY_ID
     *
     * @param factoryId the value for EXT_CPRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @return the value of EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @param factoryName the value for EXT_CPRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.CTYPE
     *
     * @return the value of EXT_CPRODUCT_C.CTYPE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.CTYPE
     *
     * @param ctype the value for EXT_CPRODUCT_C.CTYPE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCtype(Short ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @param productNo the value for EXT_CPRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @param productImage the value for EXT_CPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @param productDesc the value for EXT_CPRODUCT_C.PRODUCT_DESC
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.CNUMBER
     *
     * @return the value of EXT_CPRODUCT_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.CNUMBER
     *
     * @param cnumber the value for EXT_CPRODUCT_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCnumber(Short cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @return the value of EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @param packingUnit the value for EXT_CPRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRICE
     *
     * @return the value of EXT_CPRODUCT_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRICE
     *
     * @param price the value for EXT_CPRODUCT_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.AMOUNT
     *
     * @return the value of EXT_CPRODUCT_C.AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.AMOUNT
     *
     * @param amount the value for EXT_CPRODUCT_C.AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @return the value of EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductRequest() {
        return productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @param productRequest the value for EXT_CPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductRequest(String productRequest) {
        this.productRequest = productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_CPRODUCT_C.ORDER_NO
     *
     * @return the value of EXT_CPRODUCT_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_CPRODUCT_C.ORDER_NO
     *
     * @param orderNo the value for EXT_CPRODUCT_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }
}