package com.lanou.entity;

import java.util.Date;

public class Loginlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String loginLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.LOGIN_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.IP_ADDRESS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.LOGIN_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date loginTime;
    
    private String year;
    

    public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @return the value of LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getLoginLogId() {
        return loginLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @param loginLogId the value for LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setLoginLogId(String loginLogId) {
        this.loginLogId = loginLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.LOGIN_NAME
     *
     * @return the value of LOGIN_LOG_P.LOGIN_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.LOGIN_NAME
     *
     * @param loginName the value for LOGIN_LOG_P.LOGIN_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.IP_ADDRESS
     *
     * @return the value of LOGIN_LOG_P.IP_ADDRESS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.IP_ADDRESS
     *
     * @param ipAddress the value for LOGIN_LOG_P.IP_ADDRESS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.LOGIN_TIME
     *
     * @return the value of LOGIN_LOG_P.LOGIN_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.LOGIN_TIME
     *
     * @param loginTime the value for LOGIN_LOG_P.LOGIN_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}