package com.lanou.mapper;

import java.util.List;

import com.lanou.bean.FactoryRecordBean;
import com.lanou.entity.Contractproduct;

public interface ContractproductMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_PRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int deleteByPrimaryKey(String contractProductId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_PRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insert(Contractproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_PRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insertSelective(Contractproduct record);

	/**
	 * 根据id查找货物
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	Contractproduct selectByPrimaryKey(String contractProductId);

	/**
	 * 根据id修改
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKeySelective(Contractproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_PRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKey(Contractproduct record);

	/**
	 * 通过id查找合同货物表
	 * 
	 * @param id
	 * @return
	 */
	 List<Contractproduct> selectByContractId(String id);
	 /**
	  * 级联删除
	  * @param contractId
	  * @return
	  */
	 int deleteByContractId(String contractId);
	 
	 /**
	     * 货物销售前十名
	     * @return
	     */
	 List<FactoryRecordBean> selectProductNumber();
}