package com.lanou.mapper;

import java.util.List;

import com.lanou.entity.Contractproduct;
import com.lanou.entity.Contractproducthis;

public interface ContractproducthisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int deleteByPrimaryKey(String contractProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insert(Contractproducthis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insertSelective(Contractproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    Contractproducthis selectByPrimaryKey(String contractProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(Contractproducthis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_PRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKey(Contractproducthis record);
    /**
     *根据历史合同id查询历史合同货物
     * @param contractHisId
     * @return
     */
    List<Contractproducthis> selectByContractHisId(String contractHisId);
}