package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.junit.runners.Parameterized.Parameters;

import com.lanou.entity.Contract;
import com.lanou.entity.Contracthis;

public interface ContracthisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int deleteByPrimaryKey(String contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insert(Contracthis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insertSelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    Contracthis selectByPrimaryKey(String contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(Contracthis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRACT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKey(Contracthis record);
    /**
     * 查询所有合同历史
     * @return
     */
   List<Contracthis> selectAllContractHis();
   /**
    * 根据厂家，查询该厂家下所有的合同信息
    * @param factoryId
    * @return
    */
   List<Contracthis> selectByFactoryId(String factoryId);
   /**
    * 求出总金额最大的合同信息
    * @return
    */
   List<Contracthis> selectMaxTotalAcount();
   /**
    * 5：求出近三月以来，合同列表
		6：求出近半年以来，合同列表
    * @return
    */
   List<Contracthis> selectContactByMonth(@Param("month")Integer month);
   /**
    * 根据年份，合同列表
    * @return
    */
   List<Contracthis> selectContactByYear(Integer year);
   
}