package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lanou.entity.Eackinglist;

public interface EackinglistMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insert(Eackinglist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKey(Eackinglist record);
	////////////////////////////////////////////////////////////////////////////////

	/**
	 * 根据id删除
	 * 
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int deleteByPrimaryKey(String packingListId);

	/**
	 * 根据id查询
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	Eackinglist selectByPrimaryKey(String packingListId);

	/**
	 * 修改
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKeySelective(Eackinglist record);

	/**
	 * 增加
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insertSelective(Eackinglist record);

	/**
	 * 查询装箱单列表
	 * 
	 * @return
	 */
	List<Eackinglist> selectAllPacking();
	/**
	 * 批量删除
	 * @param id
	 * @return
	 */
	int deletePackings(@Param("ids")String[] ids);
	

}