package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.lanou.entity.Export;

public interface ExportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPORT_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int deleteByPrimaryKey(String exportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPORT_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insert(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPORT_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insertSelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPORT_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    Export selectByPrimaryKey(String exportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPORT_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPORT_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKey(Export record);
    /**
     * 查询所有报运单
     * @return
     */
   List<Export> selectAll();
   /**
    * 根据报运单ids查询报运单
    * @param map
    * @return
    */
   List<Export> selectByExportIds(Map<String,Object>map);
   /**
    * 多条查询
    * @param ids
    * @return
    */
   List<Export> selectByExportIdss(@Param("ids") String[] ids);
   /**
    * 根据装箱单的customerContracts查到报运单
    * @param customerContracts
    * @return
    */
   List<Export> selectByCustomerContracts(@Param("customerContracts") List<String>customerContracts);
   /**
    * 根据装箱表的customerContract删除
    * @param customerContract
    * @return
    */
   int deletecustomerContracts(@Param("customerContract")String customerContract);
   
}