package com.lanou.mapper;

import java.util.List;

import com.lanou.entity.Extcproduct;
import com.lanou.entity.Extcproducthis;

public interface ExtcproducthisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int deleteByPrimaryKey(String extCproductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insert(Extcproducthis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insertSelective(Extcproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    Extcproducthis selectByPrimaryKey(String extCproductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(Extcproducthis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKey(Extcproducthis record);
    /**
     * 根据合同货物历史id查询合同货物附件
     * @param contractProductHisId
     * @return
     */
    List<Extcproducthis> selectByContractProductHisId(String contractProductHisId);
}