package com.lanou.mapper;

import com.lanou.entity.Shippingorder;

public interface ShippingorderMapper {
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insert(Shippingorder record);

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKey(Shippingorder record);
    
    //////////////////////////////////////////////////////////////////////////////////
    
    /**
     * 根据id删除
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int deleteByPrimaryKey(String shippingOrderId);
    
    
    /**
     * 根据id查询
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    Shippingorder selectByPrimaryKey(String shippingOrderId);
    
    
    /**
     * 增加
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insertSelective(Shippingorder record);

    

    /**
     * 根据id修改
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(Shippingorder record);
    
    
    
    
    
    
}