package com.lanou.mapper;

import com.lanou.entity.Syscode;

public interface SyscodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int deleteByPrimaryKey(String sysCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insert(Syscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insertSelective(Syscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    Syscode selectByPrimaryKey(String sysCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(Syscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKey(Syscode record);
}