package com.lanou.entity;

import java.math.BigDecimal;

public class Contractproducthis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String contractProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short outNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String loadingRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short boxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String packingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short finished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String exts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getContractProductId() {
        return contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @param contractProductId the value for CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setContractProductId(String contractProductId) {
        this.contractProductId = contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @param contractId the value for CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @param factoryId the value for CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @param factoryName the value for CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @param productNo the value for CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @param productImage the value for CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @param productDesc the value for CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @param cnumber the value for CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCnumber(Short cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getOutNumber() {
        return outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @param outNumber the value for CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOutNumber(Short outNumber) {
        this.outNumber = outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getLoadingRate() {
        return loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @param loadingRate the value for CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setLoadingRate(String loadingRate) {
        this.loadingRate = loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getBoxNum() {
        return boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @param boxNum the value for CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setBoxNum(Short boxNum) {
        this.boxNum = boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @param packingUnit the value for CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @param price the value for CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @param amount the value for CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @param finished the value for CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setFinished(Short finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getExts() {
        return exts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @param exts the value for CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExts(String exts) {
        this.exts = exts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @param orderNo the value for CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }
}