package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import com.lanou.bean.ContractAndProductBean;
import com.lanou.bean.FactoryRecordBean;
import com.lanou.entity.Contract;

public interface ContractMapper {
	/**
	 * 根据id删除对应的购销合同
	 * 
	 * @param contractId
	 * @return
	 */
	int deleteByPrimaryKey(String contractId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insert(Contract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int insertSelective(Contract record);

	/**
	 * 根据id查找
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	Contract selectByPrimaryKey(String contractId);

	/**
	 * 根据id修改
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKeySelective(Contract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:49:59 CST 2018
	 */
	int updateByPrimaryKey(Contract record);
    /**
     * 
     * @return
     */
    List<Contract> selectAll();
    
    /**
     * 查询出货表月统计显示
     * @param map
     * @return
     */
    List<ContractAndProductBean> showJOutProduct(Map<String , Object> map);
    /**
     * 厂家销售记录
     * @return
     */
    List<FactoryRecordBean> selectFactoryName();
}