package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.lanou.entity.Authuser;

public interface AuthuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int deleteByPrimaryKey(String authUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insert(Authuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int insertSelective(Authuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    Authuser selectByPrimaryKey(String authUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(Authuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    int updateByPrimaryKey(Authuser record);
    /**
     * 登录
     * @param map
     * @return
     */
    Authuser login(Map<String,Object> map);
    /**
     * 根据姓名查询是否存在
     * 
     * @param username
     * @return
     */
    List<Authuser> selectByName(@Param("username")String username);
    
}