package com.lanou.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Export {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.EXPORT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String exportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date inputDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.CONTRACT_IDS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String contractIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.CUSTOMER_CONTRACT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String customerContract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.LCNO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String lcno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.CONSIGNEE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.MARKS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String marks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.SHIPMENT_PORT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String shipmentPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.DESTINATION_PORT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String destinationPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.TRANSPORT_MODE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String transportMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.PRICE_CONDITION
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String priceCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.GROSS_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal grossWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.NET_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal netWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.MEASUREMENT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private BigDecimal measurement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORT_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Date createTime;
    /**
     * 货物数
     */
    private int pnum;
    /**
     * 附件数
     */
    private int extnum;

   

	public int getPnum() {
		return pnum;
	}

	public void setPnum(int pnum) {
		this.pnum = pnum;
	}

	public int getExtnum() {
		return extnum;
	}

	public void setExtnum(int extnum) {
		this.extnum = extnum;
	}

	public void setExtnum(Short extnum) {
		this.extnum = extnum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.EXPORT_ID
     *
     * @return the value of EXPORT_C.EXPORT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getExportId() {
        return exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.EXPORT_ID
     *
     * @param exportId the value for EXPORT_C.EXPORT_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExportId(String exportId) {
        this.exportId = exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.INPUT_DATE
     *
     * @return the value of EXPORT_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.INPUT_DATE
     *
     * @param inputDate the value for EXPORT_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.CONTRACT_IDS
     *
     * @return the value of EXPORT_C.CONTRACT_IDS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getContractIds() {
        return contractIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.CONTRACT_IDS
     *
     * @param contractIds the value for EXPORT_C.CONTRACT_IDS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setContractIds(String contractIds) {
        this.contractIds = contractIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.CUSTOMER_CONTRACT
     *
     * @return the value of EXPORT_C.CUSTOMER_CONTRACT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCustomerContract() {
        return customerContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.CUSTOMER_CONTRACT
     *
     * @param customerContract the value for EXPORT_C.CUSTOMER_CONTRACT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCustomerContract(String customerContract) {
        this.customerContract = customerContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.LCNO
     *
     * @return the value of EXPORT_C.LCNO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getLcno() {
        return lcno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.LCNO
     *
     * @param lcno the value for EXPORT_C.LCNO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setLcno(String lcno) {
        this.lcno = lcno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.CONSIGNEE
     *
     * @return the value of EXPORT_C.CONSIGNEE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.CONSIGNEE
     *
     * @param consignee the value for EXPORT_C.CONSIGNEE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.MARKS
     *
     * @return the value of EXPORT_C.MARKS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.MARKS
     *
     * @param marks the value for EXPORT_C.MARKS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setMarks(String marks) {
        this.marks = marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.REMARK
     *
     * @return the value of EXPORT_C.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.REMARK
     *
     * @param remark the value for EXPORT_C.REMARK
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.SHIPMENT_PORT
     *
     * @return the value of EXPORT_C.SHIPMENT_PORT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getShipmentPort() {
        return shipmentPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.SHIPMENT_PORT
     *
     * @param shipmentPort the value for EXPORT_C.SHIPMENT_PORT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setShipmentPort(String shipmentPort) {
        this.shipmentPort = shipmentPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.DESTINATION_PORT
     *
     * @return the value of EXPORT_C.DESTINATION_PORT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getDestinationPort() {
        return destinationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.DESTINATION_PORT
     *
     * @param destinationPort the value for EXPORT_C.DESTINATION_PORT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setDestinationPort(String destinationPort) {
        this.destinationPort = destinationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.TRANSPORT_MODE
     *
     * @return the value of EXPORT_C.TRANSPORT_MODE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getTransportMode() {
        return transportMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.TRANSPORT_MODE
     *
     * @param transportMode the value for EXPORT_C.TRANSPORT_MODE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setTransportMode(String transportMode) {
        this.transportMode = transportMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.PRICE_CONDITION
     *
     * @return the value of EXPORT_C.PRICE_CONDITION
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPriceCondition() {
        return priceCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.PRICE_CONDITION
     *
     * @param priceCondition the value for EXPORT_C.PRICE_CONDITION
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPriceCondition(String priceCondition) {
        this.priceCondition = priceCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.STATE
     *
     * @return the value of EXPORT_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.STATE
     *
     * @param state the value for EXPORT_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.GROSS_WEIGHT
     *
     * @return the value of EXPORT_C.GROSS_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getGrossWeight() {
        return grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.GROSS_WEIGHT
     *
     * @param grossWeight the value for EXPORT_C.GROSS_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setGrossWeight(BigDecimal grossWeight) {
        this.grossWeight = grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.NET_WEIGHT
     *
     * @return the value of EXPORT_C.NET_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getNetWeight() {
        return netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.NET_WEIGHT
     *
     * @param netWeight the value for EXPORT_C.NET_WEIGHT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setNetWeight(BigDecimal netWeight) {
        this.netWeight = netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.MEASUREMENT
     *
     * @return the value of EXPORT_C.MEASUREMENT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public BigDecimal getMeasurement() {
        return measurement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.MEASUREMENT
     *
     * @param measurement the value for EXPORT_C.MEASUREMENT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setMeasurement(BigDecimal measurement) {
        this.measurement = measurement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.CREATE_BY
     *
     * @return the value of EXPORT_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.CREATE_BY
     *
     * @param createBy the value for EXPORT_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.CREATE_DEPT
     *
     * @return the value of EXPORT_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.CREATE_DEPT
     *
     * @param createDept the value for EXPORT_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_C.CREATE_TIME
     *
     * @return the value of EXPORT_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_C.CREATE_TIME
     *
     * @param createTime the value for EXPORT_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}