package com.lanou.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Eackinglist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.PACKING_LIST_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String packingListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.SELLER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String seller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.BUYER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.INVOICE_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String invoiceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.INVOICE_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date invoiceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.MARKS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String marks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.DESCRIPTIONS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String descriptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.EXPORT_IDS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String exportIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.EXPORT_NOS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String exportNos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PACKING_LIST_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.PACKING_LIST_ID
     *
     * @return the value of PACKING_LIST_C.PACKING_LIST_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getPackingListId() {
        return packingListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.PACKING_LIST_ID
     *
     * @param packingListId the value for PACKING_LIST_C.PACKING_LIST_ID
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setPackingListId(String packingListId) {
        this.packingListId = packingListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.SELLER
     *
     * @return the value of PACKING_LIST_C.SELLER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.SELLER
     *
     * @param seller the value for PACKING_LIST_C.SELLER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setSeller(String seller) {
        this.seller = seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.BUYER
     *
     * @return the value of PACKING_LIST_C.BUYER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.BUYER
     *
     * @param buyer the value for PACKING_LIST_C.BUYER
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.INVOICE_NO
     *
     * @return the value of PACKING_LIST_C.INVOICE_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.INVOICE_NO
     *
     * @param invoiceNo the value for PACKING_LIST_C.INVOICE_NO
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.INVOICE_DATE
     *
     * @return the value of PACKING_LIST_C.INVOICE_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.INVOICE_DATE
     *
     * @param invoiceDate the value for PACKING_LIST_C.INVOICE_DATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.MARKS
     *
     * @return the value of PACKING_LIST_C.MARKS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.MARKS
     *
     * @param marks the value for PACKING_LIST_C.MARKS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setMarks(String marks) {
        this.marks = marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.DESCRIPTIONS
     *
     * @return the value of PACKING_LIST_C.DESCRIPTIONS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getDescriptions() {
        return descriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.DESCRIPTIONS
     *
     * @param descriptions the value for PACKING_LIST_C.DESCRIPTIONS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.EXPORT_IDS
     *
     * @return the value of PACKING_LIST_C.EXPORT_IDS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getExportIds() {
        return exportIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.EXPORT_IDS
     *
     * @param exportIds the value for PACKING_LIST_C.EXPORT_IDS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExportIds(String exportIds) {
        this.exportIds = exportIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.EXPORT_NOS
     *
     * @return the value of PACKING_LIST_C.EXPORT_NOS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getExportNos() {
        return exportNos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.EXPORT_NOS
     *
     * @param exportNos the value for PACKING_LIST_C.EXPORT_NOS
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setExportNos(String exportNos) {
        this.exportNos = exportNos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.STATE
     *
     * @return the value of PACKING_LIST_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.STATE
     *
     * @param state the value for PACKING_LIST_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.CREATE_BY
     *
     * @return the value of PACKING_LIST_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.CREATE_BY
     *
     * @param createBy the value for PACKING_LIST_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.CREATE_DEPT
     *
     * @return the value of PACKING_LIST_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.CREATE_DEPT
     *
     * @param createDept the value for PACKING_LIST_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PACKING_LIST_C.CREATE_TIME
     *
     * @return the value of PACKING_LIST_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PACKING_LIST_C.CREATE_TIME
     *
     * @param createTime the value for PACKING_LIST_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:49:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}